# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=Installation de $ProductName$
Welcome_MessageWelcome=%s - Bienvenue
Welcome_Message0=Vous êtes sur le point d'installer %s 2 Alpha 1.
Welcome_Message1=Il vous est vivement recommandé de quitter tous les programmes Windows en cours d'exécution avant de lancer l'installation.
Welcome_Message2=Cliquez sur Annuler pour quitter l'installation et fermez tous les programmes en cours d'exécution. Cliquez sur Suivant pour continuer le programme d'installation.
Welcome_Message3=Cliquez sur Suivant pour commencer l'installation de %s 2 Alpha 1.

License_Title=Accord de licence du logiciel
License_SubTitle=Termes et conditions d'utilisation du logiciel.
License_Message0=Veuillez lire l'accord de licence suivant. Utilisez la barre de défilement pour visualiser la suite.
License_Accept=J'&accepte les termes de l'accord de licence
License_Decline=Je n'accepte &PAS les termes de l'accord de licence

Type_Title=Type d'installation
Type_SubTitle=Choisissez les options d'installation.
Type_Message0=Choisissez votre type d'installation, cliquez ensuite sur Suivant.

Standard_Short=&Standard
Standard_Long=Thunderbird sera installé avec les options les plus courantes.

Custom_Short=&Personnalisée
Custom_Long=Vous pouvez choisir individuellement les composants qui seront installés. Recommandé pour les utilisateurs expérimentés.

Select_Title=Choix des composants
Select_SubTitle=Composants additionnels améliorant $ProductName$.
Select_Message0=Choisissez les composants additionnels que vous désirez installer, cliquez ensuite sur Suivant.

Path_Title=Dossier d'installation
Path_SubTitle=Où $ProductName$ sera installé.
Path_Message0=$ProductName$ sera installé dans le dossier suivant :

Integration_Title=Configuration des raccourcis
Integration_SubTitle=Créer des icônes
Integration_Message0=Créer des icônes pour $ProductShortName$ :

Integration_Desktop=Sur le bureau
Integration_StartMenu=Dans le dossier Programmes du menu Démarrer
Integration_QuickLaunch=Dans la barre de lancement rapide (Quick Launch)

SelectFolder_Title=Installation de $ProductName$ - Choix du dossier d'installation
SelectFolder_Message0=L'installation ajoutera des icones au dossier de programmes indiqué ci-dessous. Vous pouvez choisir un nouveau nom de dossier, ou choisir l'un des dossiers existants dans la liste. Cliquez sur Suivant pour continuer.

Advanced_Title=Installation de $ProductName$ - Paramètres avancés
Advanced_Message0=Si votre connexion Internet nécessite un serveur proxy, entrez le nom de ce serveur et les informations de port. Si votre connexion Internet ne nécessite pas de serveur proxy, laissez ces champs vides.

Install_Title=Résumé
Install_SubTitle=Prêt à commencer l'installation de $ProductName$.
Install_MessageInstall=Les composants suivants vont maintenant être installés :
Install_MessageDownload=Les composants suivants vont maintenant être téléchargés et installés :
Install_Message0=Cliquez sur Suivant pour continuer.

Downloading_Title=Téléchargement
Downloading_SubTitle=Téléchargement des composants requis…
Downloading_Blurb=L'installation télécharge les fichiers nécessaires pour installer $ProductName$.
Downloading_FileName=Téléchargement en cours :
Downloading_Time=Temps restant :

Installing_Title=Installation
Installing_SubTitle=Installation de $ProductName$…
Installing_Blurb=Installation des fichiers de l'application. 
Installing_Status=Préparation du fichier :
Installing_Component=Installation de :

Success_Title=Installation terminée
Success_Header=Installation terminée
Success_Message0=%s a été installé avec succès.
Success_Message1=Cliquez sur Terminer pour quitter l'installation.
Success_Launch=Lancer %s maintenant.

Check_Message=Le téléchargement de $ProductName$ est terminé. $ProductNameInternal$ doit maintenant être fermé pour procéder à l'installation. Cliquez sur OK pour quitter automatiquement $ProductNameInternal$ et commencer l'installation.
Check_FullMessage=$ProductNameInternal$ doit être fermé pour procéder à installation. Cliquez sur OK pour quitter $ProductNameInternal$ automatiquement et commencer l'installation.
Check_Wait=Fermeture de $ProductNameInternal$. Veuillez patienter…

Component_XPCOM=COM Multiplateformes
Component_Mail=$ProductName$
Component_Offline=Mode hors-ligne
Component_Offline_Long=Ajoute un mode hors-ligne à $ProductName$.
Component_RSS=Support RSS
Component_RSS_Long=Ajoute le support RSS à Mozilla $ProductName$.
Component_QFA=Agent de rapport qualité
Component_QFA_Long=Pour faire remonter les informations de plantage de $ProductName$
